if(NOT DEFINED KERA_SHADER_ROOT)
    message(FATAL_ERROR "KERA_SHADER_ROOT is required")
endif()

function(kera_validate_slang_entry relative_path entry_point shader_stage)
    set(shader_path "${KERA_SHADER_ROOT}/${relative_path}")
    if(NOT EXISTS "${shader_path}")
        message(FATAL_ERROR "Missing Slang shader: ${shader_path}")
    endif()

    file(READ "${shader_path}" shader_source)

    string(FIND "${shader_source}" "${entry_point}" entry_index)
    if(entry_index EQUAL -1)
        message(FATAL_ERROR "Missing Slang entry point '${entry_point}' in ${relative_path}")
    endif()

    set(stage_marker "[shader(\"${shader_stage}\")]")
    string(FIND "${shader_source}" "${stage_marker}" stage_index)
    if(stage_index EQUAL -1)
        message(FATAL_ERROR "Missing Slang stage marker '${stage_marker}' in ${relative_path}")
    endif()
endfunction()

kera_validate_slang_entry("triangle.slang" "vertexMain" "vertex")
kera_validate_slang_entry("triangle.slang" "fragmentMain" "fragment")
kera_validate_slang_entry("instanced_triangle.slang" "vertexMain" "vertex")
kera_validate_slang_entry("instanced_triangle.slang" "fragmentMain" "fragment")
kera_validate_slang_entry("instanced_triangle_many_lights.slang" "geometryVertexMain" "vertex")
kera_validate_slang_entry("instanced_triangle_many_lights.slang" "geometryFragmentMain" "fragment")
kera_validate_slang_entry("instanced_triangle_many_lights.slang" "fullscreenVertexMain" "vertex")
kera_validate_slang_entry("instanced_triangle_many_lights.slang" "lightingFragmentMain" "fragment")
kera_validate_slang_entry("damaged_helmet.slang" "helmetVertexMain" "vertex")
kera_validate_slang_entry("damaged_helmet.slang" "helmetFragmentMain" "fragment")
kera_validate_slang_entry("damaged_helmet.slang" "fullscreenVertexMain" "vertex")
kera_validate_slang_entry("damaged_helmet.slang" "fullscreenFragmentMain" "fragment")

message(STATUS "Slang shader contracts validated.")
